export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const SET_PRODUCT_FORM_DATA = 'SET_PRODUCT_FORM_DATA';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';